### ISSUE TITLE
Installation issue using `go get`

### ISSUE THREAD

**Issue by mwarkentin** [skx/github2mr#4]
Hi, I was trying to install this project using `go get`, but am getting the following error:

```
❯ go get github.com/skx/github2mr
package github.com/google/go-github/v29/github: cannot find package "github.com/google/go-github/v29/github" in any of:
	/usr/local/Cellar/go/1.13.8/libexec/src/github.com/google/go-github/v29/github (from $GOROOT)
	/Users/mwarkentin/go/src/github.com/google/go-github/v29/github (from $GOPATH)
```

Any suggestions? Do I need to prep by installing `go-github` somehow?

**Comment by skx** [comment]
I can confirm this fails for me too this evening, which is odd:

```
$ go get github.com/skx/github2mr
package github.com/google/go-github/v29/github: cannot find package "github.com/google/go-github/v29/github" in any of:
	/opt/go/src/github.com/google/go-github/v29/github (from $GOROOT)
	/home/skx/go/src/github.com/google/go-github/v29/github (from $GOPATH)
```

The dependencies _should_ have been found automatically, via the go module support.  If you __force__ the use of modules, via the `GO111MODULE` environmental variable, it seems to work, although I'm unsure why that has become necessary:

```
$ export GO111MODULE=on
$ go get github.com/skx/github2mr
go: downloading github.com/skx/github2mr v0.2.0
go: github.com/skx/github2mr upgrade => v0.2.0

$ github2mr 
Please specify your github token!
```



```

**Comment by mwarkentin** [comment]
Not sure if it's helpful but:

```
❯ go version
go version go1.13.8 darwin/amd64
```

https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k#-raw-go111module-endraw-with-go-113

**Comment by skx** [comment]
Thanks for the link; I guess with the environmental variable this should be resolved now, so I'll close :)
